# Generated by Django 3.2.12 on 2022-03-08 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_pub_multimedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoria')),
                ('status', models.BooleanField(default=True, verbose_name='Categoria Activada/Desactivada')),
                ('pub_cre', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Post_multimedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Set')),
                ('pub_cre', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('image', models.URLField(max_length=255)),
                ('Set', models.URLField(max_length=255)),
                ('status', models.BooleanField(default=True, verbose_name='Publicado/No Publicado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Set', to='users.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimedia.categoria_pub_multimedia')),
            ],
            options={
                'verbose_name': 'Set',
                'verbose_name_plural': 'Sets',
            },
        ),
    ]
