# Generated by Django 3.2.12 on 2022-03-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_multimedia',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='post_multimedia',
            old_name='Set',
            new_name='archivo_multimedia',
        ),
    ]
