# Generated by Django 3.2.12 on 2022-03-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_auto_20220307_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_multimedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/img'),
        ),
    ]
