# Generated by Django 3.2.12 on 2022-03-16 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escrito', '0004_auto_20220316_1828'),
        ('multimedia', '0004_alter_post_multimedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_multimedia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Set', to='escrito.autor'),
        ),
    ]
