# Generated by Django 3.2.12 on 2022-03-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0005_alter_post_multimedia_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_multimedia',
            name='archivo_multimedia',
            field=models.FileField(max_length=255, upload_to='app/static/media/video'),
        ),
    ]
