# Generated by Django 3.2.12 on 2022-03-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0006_alter_post_multimedia_archivo_multimedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_multimedia',
            name='archivo_multimedia',
            field=models.FileField(max_length=255, upload_to='video'),
        ),
        migrations.AlterField(
            model_name='post_multimedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
