# Generated by Django 3.2.12 on 2022-04-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0008_post_multimedia_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_multimedia',
            name='slug',
            field=models.CharField(max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
