# Generated by Django 3.2.12 on 2022-03-08 04:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_pub_escrita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoria')),
                ('status', models.BooleanField(default=True, verbose_name='Categoria Activada/Desactivada')),
                ('pub_cre', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Post_escrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Publicado/No Publicado')),
                ('pub_cre', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('pub_mod', models.DateField(auto_now=True, verbose_name='Fecha Modificación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escrito.categoria_pub_escrita')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
