# Generated by Django 3.2.12 on 2022-03-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_escrito',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/img'),
        ),
    ]
