# Generated by Django 3.2.12 on 2022-03-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrito', '0002_alter_post_escrito_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_escrito',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/media/img'),
        ),
    ]
