# Generated by Django 3.2.12 on 2022-03-16 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escrito', '0003_alter_post_escrito_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Autor')),
            ],
        ),
        migrations.AlterField(
            model_name='post_escrito',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escrito.autor'),
        ),
    ]
