# Generated by Django 3.2.12 on 2022-03-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrito', '0006_alter_post_escrito_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_escrito',
            name='description',
            field=models.CharField(max_length=510, verbose_name='Descripción'),
        ),
    ]
